# Generated by Django 3.0.8 on 2020-07-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20200730_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='oda',
            new_name='room',
        ),
    ]
