# Generated by Django 3.0.8 on 2020-07-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20200730_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.CharField(blank=True, choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+0', '2+0'), ('2+1', '2+1'), ('3+1', '3+1')], max_length=30),
        ),
    ]
