# Generated by Django 3.0.8 on 2020-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20200730_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.TextField(),
        ),
    ]
