# Generated by Django 3.0.8 on 2020-08-01 09:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
